import { SiGithub, SiGoogleplay } from "react-icons/si";
import { Badge } from "@/components/ui/common/badge";
import { Button } from "@/components/ui/common/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/common/card";
import { GoLinkExternal } from "react-icons/go";
import { CardContainer, CardBody, CardItem } from "@/components/ui/aceternity/3d-card";

interface ProjectCardProps {
  title: string;
  description: string;
  techStack: string[];
  imageUrl: string;
  /** Optional srcSet for responsive images (e.g. "url-400w.webp 400w, url-800w.webp 800w"). Generated by npm run images. */
  imageSrcSet?: string;
  github?: string;
  liveUrl?: string;
  playstore?: string;
  live?: boolean;
  duration?: string;
}

export default function ProjectCard(props: ProjectCardProps) {
  const {
    title,
    description,
    techStack,
    imageUrl,
    imageSrcSet,
    live,
    github,
    liveUrl,
    playstore,
    duration,
  } = props;

  const handleCardClick = () => {
    // Prioritize liveUrl, then github, then playstore
    const url = liveUrl || github || playstore;
    if (url) {
      window.open(url, '_blank', 'noopener,noreferrer');
    }
  };

  const cardContent = (
    <CardContainer className="inter-var h-full">
      <CardBody className="w-auto h-full">
        <CardItem
          translateZ="50"
          className="text-xl font-bold text-neutral-600 dark:text-[var(--text)] h-full transition-none"
        >
          <Card className="antialiased [text-rendering:optimizeLegibility] [&_*]:antialiased [&_*]:[text-rendering:optimizeLegibility] max-w-sm md:max-w-md lg:max-w-sm w-full h-full shadow-lg hover:shadow-2xl transition-[transform,shadow] duration-300 ease-out relative group/card dark:hover:shadow-white/10 dark:border-white/[0.2] border-black/[0.1] flex flex-col mx-auto cursor-pointer"
                onClick={handleCardClick}>
            <CardHeader className="flex-shrink-0">
              <CardItem
                translateZ="60"
                className="w-full h-48 rounded-2xl mb-2 overflow-hidden relative"
              >
                <img
                  src={imageUrl}
                  srcSet={imageSrcSet}
                  sizes="(max-width: 767px) 100vw, 384px"
                  alt={title}
                  width={640}
                  height={384}
                  loading="lazy"
                  decoding="async"
                  className="w-full h-48 object-cover rounded-2xl no-image-save"
                />
              </CardItem>
              <div className="text-xs text-neutral-500 dark:text-neutral-400 mb-1 transition-none">{duration}</div>
              <CardTitle className="flex items-center gap-2 transition-none text-gray-900 dark:text-[var(--text)]">
                {title}
                {live && (
                  <span className="inline-block h-2 w-2 rounded-2xl bg-emerald-500 -translate-y-0.5"></span>
                )}
              </CardTitle>
              <CardDescription className="transition-none">{description}</CardDescription>
            </CardHeader>
            <CardContent className="flex-shrink-0">
              <div className="flex flex-wrap gap-2">
                {techStack.map((tech, index) => (
                  <Badge
                    key={index}
                    variant="outline"
                    className="font-normal rounded-2xl transition-none"
                  >
                    {tech}
                  </Badge>
                ))}
              </div>
            </CardContent>
            <CardFooter className="flex justify-between mt-auto">
              {github && (
                <Button 
                  variant="ghost" 
                  size="sm" 
                  className="transition-none"
                  asChild
                  onClick={(e) => e.stopPropagation()}
                >
                  <a
                    href={github}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{ color: "var(--text)" }}
                  >
                    <SiGithub />
                    GitHub
                  </a>
                </Button>
              )}
              {playstore && (
                <Button 
                  variant="ghost" 
                  size="sm" 
                  className="transition-none"
                  asChild
                  onClick={(e) => e.stopPropagation()}
                >
                  <a href={playstore} target="_blank" rel="noopener noreferrer">
                    <SiGoogleplay />
                    App
                  </a>
                </Button>
              )}
              {liveUrl && (
                <Button
                  variant="ghost"
                  size="sm"
                  className="text-emerald-500 dark:text-emerald-400 transition-none"
                  asChild
                  onClick={(e) => e.stopPropagation()}
                >
                  <a href={liveUrl} target="_blank" rel="noopener noreferrer">
                    <GoLinkExternal />
                  </a>
                </Button>
              )}
            </CardFooter>
          </Card>
        </CardItem>
      </CardBody>
    </CardContainer>
  );

  return cardContent;
}




