name: Count Lines of Code

on: 
  push:
    branches:
      - main

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Count lines of code
      run: |
        sudo apt-get install -y cloc
        cloc .
